version: '3'


services:
    laravel-app:
      image: jniltinho/nginx-php-fpm:latest
      ports: 
        - "8080:80"
      volumes:
        - ./:/var/www/app
      networks:
        - app-network

    mysql-app:
      image: mysql:5.7.22
      ports: 
        - "3306:3306"
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: laravel
      networks:
        - app-network
      volumes:
        - /opt/docker/dbdata:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8085:80"
      environment:
        - PMA_ARBITRARY=1
      networks:
        - app-network
      depends_on:
        - mysql-app

networks: 
  app-network:
    driver: bridge
